package OopProject.AiPoweredEcommerceSystem.dto;


/**
 * Response body returned by POST /api/chat.
 *
 * <p>Wraps the plain-text reply generated by the Groq LLM so that the
 * frontend always receives a consistent JSON structure.
 */
public class ChatResponse {

    /** The AI-generated reply text. */
    private String reply;

    // ── Constructors ──────────────────────────────────────────

    public ChatResponse() {}

    public ChatResponse(String reply) {
        this.reply = reply;
    }

    // ── Getters & Setters ─────────────────────────────────────

    public String getReply()               { return reply; }
    public void setReply(String reply)     { this.reply = reply; }
}

